### ISSUE TITLE
Publishing fails for multimodule projects

### ISSUE THREAD

**Issue by NonSwag** [HangarMC/hangar-publish-plugin#12]
When running `publishAllPublicationsToHangar` in a multimodule project, the task fails with following error which is kinda contradictory
```
Could not determine the dependencies of task ':velocity:publishAllPublicationsToHangar'.
> Could not create task ':velocity:publishVelocityPublicationToHangar'.
   > Cannot set the value of task ':velocity:publishVelocityPublicationToHangar' property 'auth' of type io.papermc.hangarpublishplugin.HangarAuthService using a provider of type io.papermc.hangarpublishplugin.HangarAuthService.
```

It is also not possible to publish each module separately because it will always fail on the second one

---

Paper build file: [build.gradle.kts](https://github.com/TheNextLvl-net/commander/blob/master/paper/build.gradle.kts)
Velocity build file: [build.gradle.kts](https://github.com/TheNextLvl-net/commander/blob/master/velocity/build.gradle.kts)
Workflow logs: [failed build](https://github.com/TheNextLvl-net/commander/actions/runs/10333596335/job/28606119888)

**Comment by electronicboy** [comment]
Is this not the usual "gradle doesn't like it when you apply a plugin twice" issue?

**Comment by NonSwag** [comment]
It works for every other plugin I am using
for example, modrinth publish (minotaur) works without issues

**Comment by electronicboy** [comment]
it 100% boils down to how the plugin is designed, apparently the publish plugin is not designed in a manner that is happy to support that, hence the error message saying what it says. I'm not aware of gradle plugins or how you'd design around this issue, but, it seems to be upset due to the different "types"

**Comment by jpenilla** [comment]
This is a Gradle bug:
https://github.com/gradle/gradle/issues/17559

You need to use the workaround mentioned here: https://github.com/PaperMC/paperweight-test-plugin/blob/master/README.md
