### ISSUE TITLE
HangarVersionPublisher.uploadVersion return error with null json object

### ISSUE THREAD

**Issue by ColdeZhang** [HangarMC/hangar-publish-plugin#13]
Logs: https://mclo.gs/8C2NZg5

My gradle.kts:

```
hangarPublish {
    publications.register("plugin") {
        version.set(project.version as String) // use project version as publication version
        id.set("XXXXXX")
        channel.set("XXXXXX")
        changelog.set("XXXXXX")
        apiKey.set(System.getenv("HANGAR_TOKEN"))
        // register platforms
        platforms {
            register(Platforms.PAPER) {
                jar.set(tasks.shadowJar.flatMap { it.archiveFile })
                platformVersions.set(listOf("1.20.1-1.20.6","1.21.x"))
            }
        }
    }
}
```

> `XXXXXX` has replaced in my real kts, this just for a view & check.

## Desc

Seems like jar file uploaded with some error return, but err-msg parese failed.

**Comment by ColdeZhang** [comment]
I think maybe because of the wrong http code assert in code?

As I noticed in Hangar Api, this [upload api](https://hangar.papermc.io/api-docs#post-/api/v1/projects/-slug-/upload) return a `201` for success. Instead of `200` used in [HangarVersionPublisher: 81](https://github.com/HangarMC/hangar-publish-plugin/blob/c1a78c20af83eb5f8bb3f5ef5a96b6eba4ddb813/plugin/src/main/java/io/papermc/hangarpublishplugin/internal/HangarVersionPublisher.java#L81).

**Comment by kennytv** [comment]
The docs are wrong unfortunately, it should always return 200. Is there anything between you and our servers that would interfere with the returned data giving you a different return code?

**Comment by ColdeZhang** [comment]
Now it's returing and show err response.
