### ISSUE TITLE
Add support for jetbrains changelog gradle plugin

### ISSUE THREAD

**Issue by TheMeinerLP** [HangarMC/hangar-publish-plugin#2]
A very big impovement for future is to add [JetBrains Changelog](https://github.com/JetBrains/gradle-changelog-plugin) plugin to auto parse for versions

**Comment by TheMeinerLP** [comment]
Okay, i hold here a example for integration with this gradle

**Comment by jpenilla** [comment]
I have no idea what you mean by that, if you need help figuring out how to set it up you can ask in `#build-tooling-help` on the Paper Discord.
